export const ADD_INGREDIENT = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_ERROR = 'SET_ERROR';

export const ORDER_SUCESS = 'ORDER_SUCESS';
export const ORDER_FAIL = 'ORDER_FAIL';
export const SET_PURCHASING = 'SET_PURCHASING';
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';